### ISSUE TITLE
Swift Package Manager Support is broken

### ISSUE THREAD

**Issue by phil1995** [google/google-api-objectivec-client-for-rest#400] opened 2020-09-28 11:08 UTC
I have added the dependency for `GoogleAPIClientForREST_Drive` in a completely new and clean project using the Swift Package Manager in Xcode. An `import GoogleAPIClientForREST_Drive` fails with: `Could not build Objective-C module 'GoogleAPIClientForREST_Drive'`. And there is also the error: `'GTLRService.h' file not found'` in the file `GTLRDriveService.h`. Shouldn't it actually use the conditional import `@import GoogleAPIClientForRESTCore;` here?
```
#if SWIFT_PACKAGE || GTLR_USE_MODULAR_IMPORT
  @import GoogleAPIClientForRESTCore;
#elif GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRService.h
#else
  #import "GTLRService.h
#endif
```
Based on the comment from cassareh ([#351](https://github.com/google/google-api-objectivec-client-for-rest/pull/351#issuecomment-655897134)), I could fix it manually. Is this really necessary or is there another way to do it automatically? If there is no other possibility, we should probably point this out in the README, because in my opinion this is not obvious.

**Comment by thomasvl** [comment] 2020-09-28 13:09
Can you post a sample project that shows your issue so we can be sure we're looking at the same setup you are seeing the failure?

@karimhm fyi

**Comment by phil1995** [comment] 2020-09-28 13:31
Thanks for the quick response.
The sample project: [https://github.com/phil1995/GoogleDriveSPMTest](https://github.com/phil1995/GoogleDriveSPMTest)

My used Xcode version: Version 12.0.1 (12A7300)

The version of the GoogleAPIClientForREST is set to the latest commit at the current time: 4a816ec2fee215bfff66367fa1aca194813540e5

**Comment by thomasvl** [comment] 2020-09-29 20:19
@karimhm Can you possibly take a look at this?  It's likely going to be a little while before I'm able to look.

**Comment by karimhm** [comment] 2020-09-30 12:47
<img width="1280" alt="Swift PM issue" src="https://user-images.githubusercontent.com/6138012/94686428-b9729e00-0322-11eb-83cc-d5afe4f45f17.png">

After downloading the sample project provided above and running it under **Xcode Version 12.0 (12A7209)**. I got the error above where the `SWIFT_PACKAGE` flag is defined and undefined at the same time. This issue is related to Xcode and is present since version 11.

**Comment by thomasvl** [comment] 2020-09-30 13:18
Oh, this is the problem where one part of Xcode's build, has once set of preprocessor symbols defined and another part of the build has a different set?  Do you know if anything got filed on the Swift Forums or in Feedback for this?

**Comment by karimhm** [comment] 2020-09-30 13:22
Running the following command under `GoogleAPIClientForREST` project root directory:
```bash
swift package generate-xcodeproj
```

Will generated an Xcode project that contain the following **`Preprocessor Macros`**:

For **Debug** configuration:
 - `SWIFT_PACKAGE=1`
 - `DEBUG=1`

For **Release** configuration:
 - `SWIFT_PACKAGE=1`

<img width="1008" alt="Generated project" src="https://user-images.githubusercontent.com/6138012/94690160-a8785b80-0327-11eb-97c8-a9291a51fc67.png">

The flags above should be added to fix the issue until Xcode get fixed.

**Comment by karimhm** [comment] 2020-09-30 13:22
@thomasvl Should we add something to `README.md` that describe this?

**Comment by thomasvl** [comment] 2020-09-30 13:28
> @thomasvl Should we add something to `README.md` that describe this?

Yea.  If you have the time, posting something on the Swift forums to see if this should be considered a bug/etc. wouldn't hurt so we could reference that also.

**Comment by karimhm** [comment] 2020-09-30 14:00
> Oh, this is the problem where one part of Xcode's build, has once set of preprocessor symbols defined and another part of the build has a different set? Do you know if anything got filed on the Swift Forums or in Feedback for this?

I posted about it at the Swift forum (https://forums.swift.org/t/unable-to-compile-swift-package-when-used-in-xcode/36081) but nothing got filled.

**Comment by karimhm** [comment] 2021-01-01 11:12
This happens due to a bug in Xcode  [SR-14011](https://bugs.swift.org/browse/SR-14011).

**Comment by ChrisPearce** [comment] 2021-03-31 22:55
In the [Google/GTMAppAuth](https://github.com/google/GTMAppAuth) repository, the same problem was addressed by the approach implemented in pull request <https://github.com/google/GTMAppAuth/pull/116>.

Could a similar approach help resolve the problem in this repository?

**Comment by thomasvl** [comment] 2021-04-01 12:27
Not sure.  GTMAppAuth only seems to have one package/subpackage, so what it it has to do for imports appears like it might be simpler.  The conditionals needed to support SwiftPM+CocoaPods for these differences has been the stumbling block because Xcode doesn't have consistent C Preprocessor defines between building the package and something depending on the package (via SwiftPM).

**Comment by thomasvl** [comment] 2021-04-01 17:41
@karimhm that doesn't seem like the right SR number.  Do you have the correct one?

**Comment by karimhm** [comment] 2021-04-10 16:42
> @karimhm that doesn't seem like the right SR number. Do you have the correct one?

I reported a new bug regarding the issue [SR-14469](https://bugs.swift.org/browse/SR-14469).

**Comment by markd2** [comment] 2021-04-23 15:12
Hi!  Is there a workaround I can use here?  Making a simple standOlone project and SPMining in the core library and the two Drive libraries. When using `import GoogleAPIClientForREST`, getting the error _No such module 'GoogleAPIClientForREST'_. Tried generating the xcode project per earlier post here, and saw the same settings as in the screenshot, and building my sample project yields the same result.  Xcode Version 12.2 (12B45b), Catalina 10.15.6 (19G73).

Is just the framework downloadable from somewhere?

**Comment by Goule** [comment] 2021-04-27 13:05
Hello,
Same issue for me after adding this library with SPM (core + youtube) : 
<img width="1559" alt="Capture d’écran 2021-04-27 à 15 04 48" src="https://user-images.githubusercontent.com/21126201/116246131-fba17800-a769-11eb-98c0-f7955fd99215.png">
I stay on cocoapods since this is not fixed :)

**Comment by floriangbh** [comment] 2021-05-24 09:50
> Hello,
> Same issue for me after adding this library with SPM (core + youtube) :
> <img alt="Capture d’écran 2021-04-27 à 15 04 48" width="1559" src="https://user-images.githubusercontent.com/21126201/116246131-fba17800-a769-11eb-98c0-f7955fd99215.png">
> I stay on cocoapods since this is not fixed :)

Hello, 

I have the same issue, any idea how to fix it? 

Thanks

**Comment by ryango** [comment] 2021-05-24 21:00
If you manually include GTLR.framework either by building from source or downloading from cocoapods and set GTLR_BUILT_AS_FRAMEWORK=1 in your build preprocessor macros, you can include everything else via SPM. GoogleSignIn apparently also includes GTLR so you may have duplicate definitions if you use that.

**Comment by phil1995** [comment] 2021-05-24 21:16
Ah the moment you need to set the **Preprocessor Macros** in your project to 'SWIFT_PACKAGE=1' as described in karimhm's screenshot.

**Comment by martinhoeller** [comment] 2021-06-26 10:06
This is still broken and I don't really understand how to apply the workaround. Should I still add the Swift Package and then modify the checked out code?
Please provide some more information if possible.

**Comment by phil1995** [comment] 2021-06-26 10:16
You can add the Swift Package normally via Xcode. At the moment it is also necessary to add the `Preprocessor Macros` in the build settings as shown in the [screenshot of karimhm](https://github.com/google/google-api-objectivec-client-for-rest/issues/400#issuecomment-701386862).

**Comment by martinhoeller** [comment] 2021-06-26 15:12
I added the package, opened its root folder in the terminal and created the project file with `swift package generate-xcodeproj`.

When I open the project Xcode shows me several warnings like this:
<img width="372" alt="Screenshot 2021-06-26 at 17 06 30" src="https://user-images.githubusercontent.com/5726765/123517462-53445d00-d6a1-11eb-9582-af234ad7e433.png">

but the preprocessor macro is there. Still my project does not compile:
<img width="636" alt="Screenshot 2021-06-26 at 17 11 51" src="https://user-images.githubusercontent.com/5726765/123517502-9f8f9d00-d6a1-11eb-8671-60f571bfec01.png">
Am I missing something here?

**Comment by memfrag** [comment] 2022-04-24 19:04
It is most likely an error for module public headers to rely on SWIFT_PACKAGE, as they will be processed in contexts where SWIFT_PACKAGE is not defined. This is not a bug in Xcode, it is how it's supposed to work. The client of the package is not supposed to define it.

If the header can't be rewritten without relying on SWIFT_PACKAGE, such as by reordering the #if-#elif-#else so that SWIFT_PACKAGE is the #else case, I would instead suggest that a different define is introduced that one can specify in one's app without having to use a workaround where SWIFT_PACKAGE is defined "incorrectly" in the app build settings, because it can cause other problems with other code that uses SWIFT_PACKAGE correctly.

**Comment by karimhm** [comment] 2022-04-26 00:42
> It is most likely an error for module public headers to rely on SWIFT_PACKAGE, as they will be processed in contexts where SWIFT_PACKAGE is not defined. This is not a bug in Xcode, it is how it's supposed to work. The client of the package is not supposed to define it.
> 
> If the header can't be rewritten without relying on SWIFT_PACKAGE, such as by reordering the #if-#elif-#else so that SWIFT_PACKAGE is the #else case, I would instead suggest that a different define is introduced that one can specify in one's app without having to use a workaround where SWIFT_PACKAGE is defined "incorrectly" in the app build settings, because it can cause other problems with other code that uses SWIFT_PACKAGE correctly.

In order to write code that does not depend on `SWIFT_PACKAGE` flag the project file structure need to be changed, doing this will break the library when used with other build systems (CocoaPods, Carthage, git submodules, Ninja, proprietary, ...).

**Comment by thomasvl** [comment] 2022-05-16 16:17
fyi - we're getting close to cutting a 2.0 release that reshuffles the source and should hopefully resolve these issues once and for all.

(the 2.0 version will be because the reshuffle could break some specific setups for imports, but we're trying to make the changes minimal)

**Closed** 2022-05-24 18:23 UTC
